apiVersion: v1
kind: Pod

metadata:
  name: pod-with-config-map
  labels:
    name: pod-with-config-map

spec:
  containers:
    - name: pod-with-config-map
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config