# like deployment definition, job definition contains pod definition within spec-->template
apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # three replicass
  parallelism: 3 # create 3 pod simultaneously instead of creating one at a time
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3', '+', '5']
      restartPolicy: Never