apiVersion: v1
kind: Pod

metadata:
  name: pod-with-secret
  labels:
    name: pod-with-secret

spec:
  containers:
    - name: pod-with-secret
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret